graph TD
wartung --> INCIDENT_RESPONSE[INCIDENT RESPONSE]
wartung --> LOGGING_UND_ALARMIERUNG[LOGGING UND ALARMIERUNG]
wartung --> PATCH_MANAGEMENT[PATCH MANAGEMENT]
wartung --> SICHERHEITSUEBERWACHUNG[SICHERHEITSUEBERWACHUNG]
wartung --> todo[TODO]
todo --> DEV_SEC_OPS[DEV SEC OPS]
todo --> IMAGE_SCANNING[IMAGE SCANNING]
todo --> SECRET_SCANNING[SECRET SCANNING]
wartung[WARTUNG]
INCIDENT_RESPONSE[INCIDENT RESPONSE]
LOGGING_UND_ALARMIERUNG[LOGGING UND ALARMIERUNG]
PATCH_MANAGEMENT[PATCH MANAGEMENT]
SICHERHEITSUEBERWACHUNG[SICHERHEITSUEBERWACHUNG]
todo[TODO]
DEV_SEC_OPS[DEV SEC OPS]
IMAGE_SCANNING[IMAGE SCANNING]
SECRET_SCANNING[SECRET SCANNING]
click todo "todo"
classDef phaseFill fill:#2A9D8F,color:#FFFFFF,stroke:#000,stroke-width:1.5px;
class wartung,INCIDENT_RESPONSE,LOGGING_UND_ALARMIERUNG,PATCH_MANAGEMENT,SICHERHEITSUEBERWACHUNG,todo,DEV_SEC_OPS,IMAGE_SCANNING,SECRET_SCANNING phaseFill;
